export const DATE_FORMATS = {
  DATE_COMMON_DISPLAY: 'DD/MM/YYYY',
  DATE_LOCAL_DISPLAY: 'l',
  DATE_PICKER_DISPLAY: 'dd MMM yyyy',
  DATE_PICKER_DISPLAY_WITH_TIME: 'DD MMM YYYY HH:mm',
  DATE_PICKER_EDIT: 'dd MM yyyy',
  DATE_PICKER_KEYBOARD: 'dd-MM-yyyy',
  DATE_PICKER_MASK: '__ __ ____',
  DATE_PICKER_PLACEHOLDER: 'dd.MM.yyyy',
  DATE_PICKER_WITH_TIME: 'dd MMM yyyy, HH:mm',
  DATE_TIME_COMMON_DISPLAY: 'DD/MM/YYYY HH:mm',
  DB_NO_TIME_ZONE: 'YYYY-MM-DDTHH:mm:ss',
  TIME_COMMON_DISPLAY: 'HH:mm:ss',
};
