export const LOCATION_MANAGEMENT = 'LOCATION_MANAGEMENT';
export const LOCATION_PACKAGE_MANAGEMENT = 'LOCATION_PACKAGE_MANAGEMENT';
export const YANDEX_MAPS = 'YANDEX_MAPS';
export const FAVORITE_LOCATION_MANAGEMENT = 'FAVORITE_LOCATION_MANAGEMENT';
export const FORBIDDEN_AREA = 'FORBIDDEN_AREA';
export const HELP_CONTENT_MANAGEMENT = 'HELP_CONTENT_MANAGEMENT';
export const TOOLTIP_MANAGEMENT = 'TOOLTIP_MANAGEMENT';
export const COMPETITION_TEMPLATE_MANAGEMENT =
  'COMPETITION_TEMPLATE_MANAGEMENT';
export const FOXORING_COMPETITION_TYPE = 'FOXORING_COMPETITION_TYPE';
