export const ACTIVE_FOX_EVENT = 'ACTIVE_FOX';
export const CURRENT_LOCATION_EVENT = 'CURRENT_LOCATION';
export const COMPETITION_RESULT_EVENT = 'COMPETITION_RESULT';
export const COMPETITION_IS_EXPIRED_EVENT = 'COMPETITION_IS_EXPIRED';
