DROP TYPE IF EXISTS ORGANIZATION_STATUS;
CREATE TYPE ORGANIZATION_STATUS AS ENUM ('NEW', 'DECLINED', 'ONBOARDING', 'ACTIVE', 'DEACTIVATED');


ALTER TABLE fh_admin.organization
    ADD COLUMN status ORGANIZATION_STATUS NOT NULL DEFAULT ('ACTIVE'),
    ADD COLUMN created TIMESTAMP NOT NULL DEFAULT (now()), --immutable
    ADD COLUMN last_status_change TIMESTAMP NOT NULL DEFAULT (now()),
    ADD COLUMN member_count INT NOT NULL DEFAULT (5);

ALTER TABLE fh_admin.organization
    ALTER COLUMN status SET DEFAULT ('NEW'),
    ALTER COLUMN member_count DROP DEFAULT;

