package com.itechart.foxhunt.domain.enums;

public enum NotificationType {

    ERROR, INITIAL_NOTIFICATION, ACTIVE_FOX, PARTICIPANT_START, COMPETITION_START, COMPETITION_CLOSED, READY_TO_START,
    CURRENT_LOCATION, PARTICIPANT_DISCONNECTED, COMPETITION_RESULT, PARTICIPANT_FINISH, FOX_FOUND, PARTICIPANT_TIME_IS_UP, USER_IS_OUT_OF_POLYGON,
    COMPETITION_IS_EXPIRED
}
