#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

declare -a DIRECTORY_ARRAY=("fox-hunt-front/src" \ 
      "fox-hunt-organization-backend/src" "common-front/bin/src" \ 
      "fox-hunt-api-gateway/src" "fox-hunt-feature-service/src")

for val in ${DIRECTORY_ARRAY[@]}; do
  echo $val
  declare IS_FOLDER_CHANGE=$(git diff --cached --name-only | grep $val/)

  echo "IS_FOLDER_CHANGE  --> + $IS_FOLDER_CHANGE"

 if [[ $IS_FOLDER_CHANGE ]]; then cd $val && npm run lint && cd ../..; fi

  if [[ $? -ne 0 ]] ; then
    echo "Unable to commit during lint rules in folder  --> $val"
    exit 1
  fi
done
